server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
   
jsonorder:
    rabbitmq:
      exchange: jsonorder.exchange
      queue: jsonorder.queue
      routingkey: jsonorder.routingkey

xmlorder:
    rabbitmq:
      exchange: xmlorder.exchange
      queue: xmlorder.queue
      routingkey: xmlorder.routingkey

